### ISSUE TITLE
Invalid JSON format anyway

### ISSUE THREAD

**Issue by KamiyaMinoru** [aiktb/furiganamaker#10]
### Describe the bug

I tried to 1. modify one item 2. remove all rules 3. just save with the original rules, 
it warns me JSON is invalid (and unable to save).

![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/02bebbaf-d669-46ca-bcf5-6f3d0b2a05ba)
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/df67c345-0fe9-4e97-b37a-c2463bdc5d74)
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/20a291b2-6735-41bf-aec2-7fbaa30b11b8)

### Reproduction

1. modify the rule, 
from [{"domain": "twitter.com","selector": "div[lang='ja'] span","dynamic": true,"enabled": **true**},
to [{"domain": "twitter.com","selector": "div[lang='ja'] span","dynamic": true,"enabled": **FALSE**}, ...
→ Invalid JSON

2. remove all contents in the rule box
→ Invalid JSON

3. undo all steps by 2 times ctrl+Z
→ Invalid JSON

### Expected behavior

Clear the rule

### Browser

Edge

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't [already an issue](https://github.com/aiktb/FuriganaMaker/issues) that asks for the same feature to avoid creating a duplicate.
- [X] Read the [Contributing Guidelines](https://github.com/aiktb/FuriganaMaker/blob/main/.github/CONTRIBUTING.md).
- [ ] I would like to fix this BUG via a PR.

**Comment by aiktb** [comment]
The empty string `''` is indeed considered invalid JSON, to clear all the rules here it should be written `[]`, I will modify this part of the logic to work well with empty strings.

In addition, subsequent releases will add a new UI, not just a JSON editor, to enhance the user experience and reduce the likelihood of errors.

"Can't change rules" is a bug, I'll fix it soon.

**Comment by KamiyaMinoru** [comment]
And a quick question about this: Do I need to write rules site by site to make Furigana Maker work?
Because I do not find a way to make it work on most web sites (while JSON is not actually editable):

examples:

Out of work
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/7c6bad09-80bd-4264-81d6-645def9003c4)

partially works
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/0e821cd5-0011-480f-acd5-973f7b75fca9)

Fully works (but seem hotkeys not work: in this case, alt+shift+J or alt+J brings no change)
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/3811c47a-ef3a-4df4-8cfe-79df0e42012f)
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/9bcce85c-58d7-45ef-9c2e-55368ed5cdb5)

Thank you again.

**Comment by aiktb** [comment]
This issue is tricky, in my development environment this extension works fine, only appears after uploading Chrome/Edge Store, even in Firefox he is normal, need more time to research.

**Comment by KamiyaMinoru** [comment]
I am using Edge ver.  109.0.1518.140 with Windows 7, in case you are interested in this infor.

**Comment by aiktb** [comment]
Finished the fix and now the rule editor is fully GUI operated.
![Snipaste_2023-11-22_16-41-54](https://github.com/aiktb/FuriganaMaker/assets/104723527/135f15e4-077c-4272-a6dc-cfcf2276f814)
![Snipaste_2023-11-22_16-42-06](https://github.com/aiktb/FuriganaMaker/assets/104723527/4d1c5d41-84c9-4608-81e0-2348af9f6f99)

It is still possible to import and export JSON configs, I changed the implementation and tested this in dev mode which works fine, I am not sure if the extensions downloaded from the Extension Store will work properly due to the strange phenomenon before, but this is not a big problem, even if the JSON config can not be edited, the Rule editor will work fine.

For those who don't know CSS selector, you can add furigana to most of the Japanese text on the page by simply filling the `selector` field with `body`, I've included this in the user guide. Most blogs and news sites have content that is hardly ever dynamically updated, which has no significant impact on performance, but this can be very bad for sites that dynamically update their content as often as twitter, so for twitter you will still need to manually write the `selector` field.

Waiting for the extension store to review and approve.

**Comment by aiktb** [comment]
It's been confirmed on the Chrome Web Store that the latest version [v1.1.0](https://chromewebstore.google.com/detail/furigana-maker/heodojceeinbkfjfilnfminlkgbacpfp) fixes this issue, Edge still needs a little more time to go through the vetting process.

Please re-open this issue if there are still bugs related to this.
