### ISSUE TITLE
Hot key to turn on-off / dymantic space adjustment

### ISSUE THREAD

**Issue by KamiyaMinoru** [aiktb/furiganamaker#11]
### Is your feature request related to a problem? Please describe.

To put (or prepare to put) hiragana, when this extension is turned on, it will create spaces between words (Kanji)
Even it is under on-hover mode, we can see the layout of the contents changed, as the below pictures showed
Sometimes these spaces between words cause a little inconvenience in reading
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/37d2d379-10db-42c3-820f-24416cc3f34b)
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/5031d3df-77ad-4638-a70c-5f451e3d5124)

I tried to set hot-key, but it actually is not "turn on-off" Furigana, but call (pop-up) menu.
![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/b9af61dc-f5db-49d8-a18f-b570d9d161d1)

### Describe the solution you'd like

I would like to ask if it is possible to have a hot-key to "turn on-off" Furigana,
that can make the reader to switch between "normal layout" (easier to read) and "show Hiragana"?
Or, it does not pre-leave space to put Hiragana, but create space "dynamically" when on-hover (in hover mode)?

![image](https://github.com/aiktb/FuriganaMaker/assets/78710607/5fb3cd55-4ca6-4ed8-a6e2-1ad9731957a7)

Hope my description is not confusing.

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
- [ ] I would like to implement this feature via a PR.

**Comment by aiktb** [comment]
In order to implement the hover mode, the `<ruby>` tag corresponding to furigna has been injected into the interface, but  spacing automatically added by the browser, which is completely controlled by the browser, and as far as I know, there is no CSS property that can control the spacing between ruby characters.

It is possible to not show the spacing between ruby characters on hover, e.g. by using the CSS `display` property, but as you can see in the image below this would cause a serious layout offset and should not be done.
[screen-recorder-wed-nov-08-2023-08-44-09.webm](https://github.com/aiktb/FuriganaMaker/assets/104723527/87d73b17-21fe-457c-8ae2-0bfc4ab88de7)

Call popup menu is the default shortcut provided by all browsers for the expansion, developers can not change, please use for this "Switch furigana display on all pages" to add a shortcut, which may conflict with some browsers registered shortcuts do not work, I recommend that you try to replace other shortcuts.
![Snipaste_2023-11-08_08-49-01](https://github.com/aiktb/FuriganaMaker/assets/104723527/418c341d-b986-4511-a3ec-de93000ca8b3)

**Comment by KamiyaMinoru** [comment]
Thanks for explaining in detail! Let me try which shortcuts will work
By the way, the video example you displayed... I will say like it (minimized ruby impact to the article layout / reading)

**Comment by aiktb** [comment]
It was found that ToggleDisplay and ToggleHoverMode shortcuts were not working, fixed in the new version.
