### ISSUE TITLE
Not working on an AWS Doc

### ISSUE THREAD

**Issue by manoger** [aiktb/furiganamaker#221]
### Describe the bug

Hello!
The content in https://catalog.workshops.aws/well-architected-sustainability/ja-JP/0-region-selection does not produce furigana

### Reproduction

1. Access the website try to show furigana with the extension on Google Chrome

### Expected behavior

Expected to show furigana

### Browser

Chrome

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't [already an issue](https://github.com/aiktb/FuriganaMaker/issues) that asks for the same feature to avoid creating a duplicate.
- [X] Read the [Contributing Guidelines](https://github.com/aiktb/FuriganaMaker/blob/main/.github/CONTRIBUTING.md).
- [ ] I would like to fix this BUG via a PR.

**Comment by aiktb** [comment]
Hi! Thanks for your feedback. I checked the webpage structure of AWS Doc and found that it was not correctly marked as a Japanese webpage, so the extension didn't automatically add furigana to it.

![image](https://github.com/user-attachments/assets/37c4413a-1623-40c1-888b-ae779a53958b)


Solution:
Since this extension obtains the target text through `[lang='ja']`, on pages that do not have the `lang` attribute correctly marked, you need to manually add a custom rule to automate it:

```txt
domain: catalog.workshops.aws
selector: body *
```

After testing, the effect of `body *` is better...

Steps:
![image](https://github.com/user-attachments/assets/cccb4564-bfce-446a-b7c0-ca848d54ed66)
![image](https://github.com/user-attachments/assets/a4951ec7-bcb5-4a63-99d0-3000558f56af)

Note: You may need to re-add this rule soon, as I'm planning to rewrite the rule editor to make it simpler and support including/excluding pages, and I may introduce breaking changes in the process.
