### ISSUE TITLE
Enabling the extension will affect the style of the page

### ISSUE THREAD

**Issue by suhanyujie** [aiktb/furiganamaker#313]
### Describe the bug

Enabling the extension will affect the style of the page. As shown in the figure:
![image](https://github.com/user-attachments/assets/edca091a-7cf1-4ff1-b8f1-989d0627cce7)

If the extension is turned off, the page displays normally.

### Reproduction

eg：https://news.yahoo.co.jp/

### Expected behavior

Expect the page to display normally

### Browser

Edge

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 19.12 GB / 31.75 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.6 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (131.0.2903.86)
    Internet Explorer: 11.0.26100.1882
```

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't [already an issue](https://github.com/aiktb/FuriganaMaker/issues) that asks for the same feature to avoid creating a duplicate.
- [X] Read the [Contributing Guidelines](https://github.com/aiktb/FuriganaMaker/blob/main/.github/CONTRIBUTING.md).
- [ ] I would like to fix this BUG via a PR.

**Comment by aiktb** [comment]
I will try it today. You can add a rule on the options page to exclude this domain to reduce the impact.
```txt
news.yahoo.co.jp
```

![image](https://github.com/user-attachments/assets/1f5cc101-1227-4d8e-b436-0b7b0a985510)


![image](https://github.com/user-attachments/assets/e6bfb160-2d47-49ba-994c-de87906e545f)

I have encountered similar problems on Twitch. This is always highly coupled with the implementation of the source website, making it difficult to troubleshoot.

**Comment by aiktb** [comment]
Clearly the site has not reached a "stable state" by the time the `load` event completes, inserting new nodes into its DOM breaks the site.

An obvious approach would be to add a delay, perhaps a few hundred milliseconds, and I could add an option in the Options page for users to enter the delay they want (default is 0).

Should the delay be enabled for all sites? I'm not sure users would accept a few hundred milliseconds of delay on all available sites, but I also think it shouldn't be enabled on specific domains, because the current custom rules are complex enough that their complexity should be carefully controlled.

There is also the issue that different CPU performance should have different delay requirements.

I want to keep this feature as simple as possible, leave your comments.

**Comment by aiktb** [comment]
Today I finally had time to look at this problem. It turned out that I forgot to exclude the `script` tag when modifying the DOM. I should only modify the visible node. 😂

Another important reason is that I shouldn't call `document.normalize()` on a third-party web page. For some reason, the style sheet injected by "CSS-in-JS" in the web page was lost after calling it. This is also the reason why Twitch.tv was broken
